sudo: required

services:
  - docker

script:
  - make up --no-print-directory
  - make install_go_deps --no-print-directory
  - make test --no-print-directory
  - make cli_build_all --no-print-directory
