version: '2'

services:

  wiremock:
    image:      ${WIREMOCK_IMAGE}
    entrypoint: java -Xms512M -Xmx1024M -jar wiremock.jar
    volumes:
      - ${PWD}/mocks/__files:/wiremock/__files:cached
      - ${PWD}/mocks/mappings:/wiremock/mappings:cached
    ports:
      - 8080:8080

  go:
    image:       ${GO_IMAGE}
    command:     /bin/sh -c "while [ 1 ]; do sleep 3600; done"
    working_dir: /go/src/${GO_PKG_SRC_PATH}
    volumes:
      - ${PWD}/gitlab:/go/src/${GO_PKG_SRC_PATH}/gitlab:consistent
      - ${PWD}/cli:/go/src/${GO_PKG_SRC_PATH}/cli:consistent
      - ${PWD}/integration:/go/src/${GO_PKG_SRC_PATH}/integration:consistent
      - ${PWD}/Makefile:/go/src/${GO_PKG_SRC_PATH}/Makefile:consistent
      - ${PWD}/mocks:/go/src/${GO_PKG_SRC_PATH}/mocks:cached
